title: Abhey Rana
description: Hey there! This blog is all about the experiences that I collect about programming, competitive coding, computer science, software development ...and other amazing stuff that one comes across in the process of learning and becoming a geek.
author: Abhey Rana
logo: /static/img/avatar.png
image: /static/img/avatar.png
github: https://github.com/Abhey
about: Freelance developer
type: blog

baseurl: ""
url: http://abheyrana.me

allowsearch: true

disqus_shortname: abheyrana
google_analytics: UA-111185831-1

social: 
  name: Abhey Rana
  links:
    - https://www.facebook.com/Abhey.Rana.Useless
    - https://www.linkedin.com/in/abhey-rana-55919b132/
    - https://github.com/Abhey

share:
  twitter_username: RanaAbhey


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
